name: CI

on:
  push:
    branches: [main]
    tags-ignore: ['v*']
  pull_request:
    branches: [main]
  workflow_call:

concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    env:
      CI: true
      NX_DAEMON: false
    steps:
      - uses: actions/checkout@v4 # 53c6a6ce9a51b2e87a81ecb51528be3c65f314a4 # v4.2.2
        with:
          fetch-depth: 0

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v4 # a8ce42a4a6697706293e562e07d3055dd2b21a8b # v4.1.9
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          HUSKY: '0'

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

  test:
    name: Test
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    env:
      CI: true
      NX_DAEMON: false
    steps:
      - uses: actions/checkout@v4 # 53c6a6ce9a51b2e87a81ecb51528be3c65f314a4 # v4.2.2
        with:
          fetch-depth: 0

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v4 # a8ce42a4a6697706293e562e07d3055dd2b21a8b # v4.1.9
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          HUSKY: '0'

      - name: Test
        run: yarn test --skip-nx-cache

      - name: Coverage
        run: yarn test:coverage --run

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    env:
      CI: true
      NX_DAEMON: false
    steps:
      - uses: actions/checkout@v4 # 53c6a6ce9a51b2e87a81ecb51528be3c65f314a4 # v4.2.2
        with:
          fetch-depth: 0

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v4 # a8ce42a4a6697706293e562e07d3055dd2b21a8b # v4.1.9
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          HUSKY: '0'

      - name: Build
        run: yarn build
